name: IaC Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Digite 'destroy' para confirmar"
        required: true
        default: "cancel"

jobs:
  destroy-validation:
    runs-on: self-hosted
    if: ${{ github.event.inputs.confirm == 'destroy' }}

    env:
      PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
      PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=backend.s3.tfbackend
        working-directory: ./iac

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -input=false
        working-directory: ./iac

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./iac
