name: IaC Pipeline

on: 
  push: 
    branches: [ main ]
    paths: [ iac/**, .github/workflows/iac.yaml ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    env:
      TF_VAR_pm_api_url: ${{ secrets.PROXMOX_API_URL }}
      TF_VAR_pm_user: ${{ secrets.PROXMOX_USER }}
      TF_VAR_pm_token_id: 'terraform-user@pve!terraform-token'
      TF_VAR_pm_token_secret: ${{ secrets.PROXMOX_TOKEN_SECRET }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        # with:
        #   terraform_version: "1.7.0"
        
      - name: Execução do Terraform Init
        run: terraform init 
        working-directory: ./iac
        
      - name: Execução do Terraform Validate
        run: terraform validate
        working-directory: ./iac

      - name: Execução do Terraform Plan
        run: terraform plan
        # env:
        #   TF_VAR_pm_api_url: ${{ secrets.PROXMOX_API_URL }}
        #   TF_VAR_pm_user: ${{ secrets.PROXMOX_USER }}
        #   TF_VAR_pm_token_id: ${{ secrets.PROXMOX_TOKEN_ID }}
        #   TF_VAR_pm_token_secret: ${{ secrets.PROXMOX_TOKEN_SECRET }}
        working-directory: ./iac
        
      # - name: Execução do Terraform Apply
      #   run: terraform apply --auto-approve
      #   working-directory: ./iac