name: IaC Pipeline

on: 
  push: 
    branches: [ main ]
    paths: [ iac/**, .github/workflows/iac.yaml ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    env:
      PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
      PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Execução do Terraform Init
        run: terraform init 
        working-directory: ./iac
        
      - name: Execução do Terraform Validate
        run: terraform validate
        working-directory: ./iac

      - name: Execução do Terraform Plan
        run: terraform plan -out=tfplan -input=false
        working-directory: ./iac
        
      - name: Execução do Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./iac